// src/tools/misc/roman-numeral-converter/RomanConverter.vue
<template>
  <div class="roman-converter">
    <!-- Arabic to Roman -->
    <div class="tool-section">
      <h2 class="section-title">{{ ui.arabicNumber }}</h2>
      <input
        v-model.number="arabicValue"
        type="number"
        :min="1"
        :max="3999"
        :placeholder="ui.arabicPlaceholder"
        class="input w-full"
      />
      <div v-if="romanValue" class="result-box">
        <span class="result-text">{{ romanValue }}</span>
        <button @click="copyToClipboard(romanValue)" class="btn-secondary ml-2">
          {{ ui.copy }}
        </button>
      </div>
    </div>

    <!-- Roman to Arabic -->
    <div class="tool-section">
      <h2 class="section-title">{{ ui.romanNumeral }}</h2>
      <input
        v-model="romanValue"
        type="text"
        :placeholder="ui.romanPlaceholder"
        class="input w-full uppercase"
      />
      <div v-if="arabicValue" class="result-box">
        <span class="result-text">{{ arabicValue }}</span>
        <button @click="copyToClipboard(String(arabicValue))" class="btn-secondary ml-2">
          {{ ui.copy }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { arabicToRoman, romanToArabic } from './utils/conversion'

interface Props {
  ui: {
    arabicNumber: string
    romanNumeral: string
    arabicPlaceholder: string
    romanPlaceholder: string
    copy: string
  }
}

const props = defineProps<Props>()

const arabicValue = ref<number>(2024)
const romanValue = ref<string>(arabicToRoman(2024))

// Watch Arabic input and convert to Roman
watch(arabicValue, (newValue) => {
  if (newValue && newValue >= 1 && newValue <= 3999) {
    try {
      romanValue.value = arabicToRoman(newValue)
    } catch (e) {
      // Invalid input, keep previous value
    }
  }
})

// Watch Roman input and convert to Arabic
watch(romanValue, (newValue) => {
  if (newValue) {
    try {
      arabicValue.value = romanToArabic(newValue.toUpperCase())
    } catch (e) {
      // Invalid input, keep previous value
    }
  }
})

function copyToClipboard(text: string) {
  navigator.clipboard.writeText(text)
}
</script>

<style scoped>
.roman-converter {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.section-title {
  font-size: 1.25rem;
  font-weight: 600;
  margin-bottom: 1rem;
}

.result-box {
  margin-top: 1rem;
  padding: 1rem;
  background: #f5f5f5;
  border-radius: 0.5rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.result-text {
  font-size: 1.5rem;
  font-weight: bold;
  font-family: monospace;
}

.uppercase {
  text-transform: uppercase;
}
</style>

// tools/converters/roman-numeral/src/RomanConverter.tsx
import React, { useState, useCallback } from 'react'
import { ClipboardIcon, ArrowsUpDownIcon } from '@heroicons/react/24/outline'
import { arabicToRoman, romanToArabic, isValidRomanNumeral } from './utils/conversion'

interface Props {
  ui: {
    arabicNumber: string
    romanNumeral: string
    arabicPlaceholder: string
    romanPlaceholder: string
    copy: string
  }
}

export default function RomanConverter({ ui }: Props) {
  const [arabicValue, setArabicValue] = useState<number>(2024)
  const [romanValue, setRomanValue] = useState<string>(arabicToRoman(2024))

  const onArabicChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const value = parseInt(e.target.value, 10)
    setArabicValue(value)
    if (value && value >= 1 && value <= 3999) {
      try {
        setRomanValue(arabicToRoman(value))
      } catch {
        // Invalid input, keep previous value
      }
    }
  }, [])

  const onRomanChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value.toUpperCase()
    setRomanValue(value)
    if (value && isValidRomanNumeral(value)) {
      try {
        setArabicValue(romanToArabic(value))
      } catch {
        // Invalid input, keep previous value
      }
    }
  }, [])

  const copyToClipboard = useCallback((text: string) => {
    navigator.clipboard.writeText(text)
  }, [])

  return (
    <div className="flex flex-col gap-6">
      {/* Arabic Number Input */}
      <div className="p-6 bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700">
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
          {ui.arabicNumber}
        </label>
        <div className="flex gap-3">
          <input
            type="number"
            value={arabicValue}
            onChange={onArabicChange}
            min={1}
            max={3999}
            placeholder={ui.arabicPlaceholder}
            className="flex-1 px-4 py-3 text-xl font-mono bg-gray-50 dark:bg-gray-900 border-2 border-gray-200 dark:border-gray-600 rounded-lg focus:border-blue-500 focus:outline-none transition-colors"
          />
          <button
            onClick={() => copyToClipboard(String(arabicValue))}
            className="px-4 py-3 bg-gray-100 dark:bg-gray-700 hover:bg-blue-500 hover:text-white border-2 border-gray-200 dark:border-gray-600 rounded-lg transition-all duration-200 group"
            title={ui.copy}
          >
            <ClipboardIcon className="w-5 h-5 text-gray-500 group-hover:text-white" />
          </button>
        </div>
      </div>

      {/* Bidirectional Arrow */}
      <div className="flex justify-center">
        <div className="flex items-center gap-2 px-4 py-2 bg-blue-100 dark:bg-blue-900 rounded-full">
          <ArrowsUpDownIcon className="w-6 h-6 text-blue-500" />
        </div>
      </div>

      {/* Roman Numeral Input */}
      <div className="p-6 bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700">
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
          {ui.romanNumeral}
        </label>
        <div className="flex gap-3">
          <input
            type="text"
            value={romanValue}
            onChange={onRomanChange}
            placeholder={ui.romanPlaceholder}
            className="flex-1 px-4 py-3 text-xl font-mono uppercase bg-gray-50 dark:bg-gray-900 border-2 border-gray-200 dark:border-gray-600 rounded-lg focus:border-blue-500 focus:outline-none transition-colors"
          />
          <button
            onClick={() => copyToClipboard(romanValue)}
            className="px-4 py-3 bg-gray-100 dark:bg-gray-700 hover:bg-blue-500 hover:text-white border-2 border-gray-200 dark:border-gray-600 rounded-lg transition-all duration-200 group"
            title={ui.copy}
          >
            <ClipboardIcon className="w-5 h-5 text-gray-500 group-hover:text-white" />
          </button>
        </div>
      </div>
    </div>
  )
}
